# Generated by Django 6.0.4 on 2026-05-02 11:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_comment_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='PublicationRating',
        ),
        migrations.RemoveConstraint(
            model_name='comment',
            name='unique_comment_user',
        ),
    ]
