# Generated by Django 6.0.4 on 2026-09-28 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_alter_comment_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='publication',
            constraint=models.UniqueConstraint(fields=('file_key',), name='file_key'),
        ),
    ]
