# Generated by Django 6.0.4 on 2026-09-28 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_publication_file_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='langauge',
            new_name='language',
        ),
    ]
